version: "2"
services:
  elsabackend-postgresql:
    image: postgres:12.3
    environment:
      - POSTGRES_USER=elsaBackend
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
